import fs from 'fs';
import path from 'path';
import yaml from 'yaml';
import { buildEntityGraph } from '../src/logic.js';

const outDir = path.resolve(process.cwd(), 'corpus');
const manifestPath = path.join(outDir, 'manifest.json');
const systemMapPath = path.join(outDir, 'system-map.yaml');
const todoPath = path.resolve(process.cwd(), 'TODO.md');

function buildMap() {
  if (!fs.existsSync(manifestPath)) {
    console.error('manifest.json not found. Run build:corpus first.');
    process.exit(1);
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  const { systemMap, missingCatalog } = buildEntityGraph(manifest.repos);

  fs.writeFileSync(systemMapPath, yaml.stringify(systemMap));
  console.log(`system-map.yaml built at ${systemMapPath}`);

  // Generate TODO.md
  if (missingCatalog.length > 0) {
    const todoContent =
      `# Backlog: Repos missing catalog-info.yaml\n\nThis file is auto-generated by the build-map script. Do not edit manually.\n\n` +
      missingCatalog
        .sort()
        .map((repo) => `- [ ] ${repo}`)
        .join('\n') +
      '\n';
    fs.writeFileSync(todoPath, todoContent);
    console.log(
      `Generated TODO.md with ${missingCatalog.length} repositories missing catalog-info.yaml.`
    );
  } else {
    fs.writeFileSync(
      todoPath,
      `# Backlog: Repos missing catalog-info.yaml\n\nAll repos have catalog-info.yaml! 🎉\n`
    );
  }
}

try {
  buildMap();
} catch (err) {
  console.error('Build map failed:', err);
  process.exit(1);
}
